version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
      - OTEL_SERVICE_NAME=challenge-weather
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
    depends_on:
      - zipkin
      - otel-collector
    networks:
      - challenge-weather

  otel-collector:
      image: otel/opentelemetry-collector:latest
      command: [ "--config=/etc/otel-collector-config.yaml" ]
      volumes:
          - ./config/otel/config.yaml:/etc/otel-collector-config.yaml:ro
      ports:
          - "4318:4318"
          - "4317:4317"
      networks:
          - challenge-weather

  zipkin:
    image: openzipkin/zipkin
    ports:
        - "9411:9411"
    depends_on:
        - otel-collector
    networks:
        - challenge-weather

networks:
    challenge-weather:
        driver: bridge